github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token:    ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

codeowners:
- path:  "*"
  owner: "@paketo-buildpacks/java-maintainers"

helpers:
  "bin/helper": "$GOMOD/cmd/helper"

package:
  repositories:   ["docker.io/paketobuildpacks/java-memory-assistant"]
  register:       true
  registry_token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

docker_credentials:
- registry: docker.io
  username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
  password: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}

dependencies:
- id:           java-memory-assistant
  uses:         docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    owner:      sap
    glob:       java-memory-assistant-(.+).jar
    repository: java-memory-assistant
    token:      ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}